# Generated by Django 5.0.3 on 2024-03-14 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_comments_created_at_comments_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="postid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comment",
                to="users.post",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="userid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
