# Generated by Django 5.0.3 on 2024-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_comments_parent_comment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100, verbose_name="post title"),
        ),
    ]
